### PR TITLE
Match sktime-dl libs name with official sktime repo

### PR DESCRIPTION
**Pull request by wangyida**
#### What does this implement/fix? Explain your changes.

Modify function name of sktime libs which are imported by sktime-dl

#### Does your contribution introduce a new dependency? If yes, which one? 

If your contribution does add a new dependency, we may suggest to initially develop your contribution in a separate
 companion package in https://github.com/sktime/ to keep external dependencies of the core sktime package to a minimum.

### CODE REVIEW

**Comment by wangyida** [comment]
@mloning Seems that we need to add a dependency of 'tsfresh' in the main repo of sktime, otherwise test cases in 'sktime_dl/deeplearning/tests' can not be passed. Should I open up another PR in 'sktime' to add dependency on 'tsfresh'?

**Comment by mloning** [comment]
Hi @wangyida thanks for picking up this work, but I'm not sure what you're trying to do. Could you give me some context?

**Comment by wangyida** [comment]
> Hi @wangyida thanks for picking up this work, but I'm not sure what you're trying to do. Could you give me some context?

Sure, it's just a simple PR where I corrected the refered libs/functions from sktime in sktime-dl. There are outdated lib names from sktime which are imported in sktime-dl.

**Comment by mloning** [comment]
Ah okay, makes sense! 

We've been working on isolating the soft dependencies better in base sktime, where exactly do we end up importing `tsfresh` in sktime-dl?  We may be able to disentangle module even further to expose common testing utility to sktime-dl without needing to install `tsfresh`

**Comment by mobiuscreek** [comment]
Hello, 

I spent sometime trying to figure out the issue. `sktime 0.4.3` has introduced some breaking changes caused by [check_imports.py](https://github.com/alan-turing-institute/sktime/blob/master/sktime/utils/check_imports.py) that checks whether any soft dependencies are missing from the environment. Because there are several imports called by `sktime-dl` from `sktime` and `tsfresh` is not required by it, it raises the exception you see. I think there is work being done at the moment and things are still fluid.

As it stands `sktime-dl` is incompatible with `sktime 0.4.3`, and I would suggest to use an older version. A temporary fix for a CI/CD would be to pin to `sktime==0.4.2.` in the sktime-dl's `requirements.txt` until the compatibility issue is fixed.

**Comment by mloning** [comment]
Hi @mobiuscreek, yes you're right, I think the purpose of this PR is to update sktime-dl to align it again with the latest stable release of sktime. I may be worth waiting for the v0.5.0 release of sktime because, as you said, that will introduce a few more changes.

**Comment by TonyBagnall** [comment]
closing prior to update of sktime-dl to v6

**Pull request closed without merging**
