### PR TITLE
Compatibility with sktime v0.6.1 

### LINKED ISSUE #74: [BUG] Problem with sktime-dl installation; cannot import e.g. sktime_dl.deeplearning
**Describe the bug**

I create a new Conda env:  `conda create -n sktime-dl python=3.6` then run: `pip install sktime-dl` but than when I try to `from sktime_dl.deeplearning import CNNClassifier` Python cannot find `sktime_dl.deeplearning`. 

I also tried to install development version of sktime-dl but the package cannot be installed as there are NumPy and h5py conflicts (Tensorflow requires older numpy and h5py). I also tried to install required NumPy and h5py before running `pip install .`, but it doesn't help.

**To Reproduce**

```
conda create -n sktime-dl python=3.6
conda activate sktime-dl
pip install sktime-dl
```
```python
from sktime_dl.deeplearning import CNNClassifier
```

**Expected behavior**

I can run: `from sktime_dl.deeplearning import CNNClassifier` 
and I can run locally Jupyter Notebooks from `examples`.

**Additional context**

**Versions**
Linux-4.19.128-microsoft-standard-x86_64-with-debian-buster-sid
Python 3.6.11 | packaged by conda-forge | (default, Aug  5 2020, 20:09:42)
NumPy 1.18.5
SciPy 1.5.4
sktime 0.4.3
sktime_dl 0.1.0

### PR DESCRIPTION
**Pull request by Riyabelle25**
#### Reference Issues/PRs
Fixes #74 , #76 

#### What does this implement/fix? Explain your changes.
This PR fixes issues #74 and #76 by updating sktime references in the code to that of `sktime v0.6.1`. Hence this resolves compatibility issues with `sktime v0.6.1`, bringing `sktime_dl` up-to-date with the latest version of sktime.
It also updates deprecated Keras code to resolve some of the build failures on running `Pytest`.

#### Tested by:
```
conda activate venv
git clone https://github.com/sktime/sktime-dl.git
cd sktime-dl
pip install  .
python
>> from sktime_dl.deeplearning import CNNClassifier
```
After this I ran `pytest` in the root directory, and confirmed that no tests are failing due to incompatibility with sktime. 
Rather they are associated with version incompatibilities of Keras, Tensorflow, and Numpy, and I debugged by updating deprecated Keras code.

### CODE REVIEW

**Comment by TonyBagnall** [comment]
hi, thanks for this, the travis checks are not currently working so dont worry too much about the errors. @mloning  could you review? I'll ask @ABostrom to take a look too

**Comment by Riyabelle25** [comment]
Hi, thanks! Currently, there's just the one test failing because of Keras.

**Comment by mloning** [comment]
@Riyabelle25 as discussed, I suggest adding the pytest decorator to see if this test fails for all networks or only one of them.

**Comment by ABostrom** [comment]
Going to go through this, today with @jnrusson1, as I'd like to get this PR'd in before dev days next week.

Really great job @Riyabelle25 looks decent.

**Comment by ABostrom** [comment]
@jnrusson1 noticed a issue and raise this in the #87 issue.

I haven't had a chance to verify this, but @Riyabelle25 if you wouldn't mind taking a closer look that would be very helpful :)

**Comment by Riyabelle25** [comment]
I've fixed linting and parametrized the networks to see which fail. Thanks, @ABostrom, @jnrusson1!

**Comment by Riyabelle25** [comment]
`2021-06-17T07:53:40.4365930Z     It seems that sktime cannot be built with OpenMP support.` 
Buildwheels for sktime on [macOS build check](https://dev.azure.com/mloning/bb1cd521-6116-4bcb-8a91-180df66c64d0/_apis/build/builds/3351/logs/110) failed :astonished: 
Has this happened before?

**Comment by mloning** [comment]
@Riyabelle25 it shouldn't be necessary to compile sktime as we provide precompiled wheels for it, not sure why it tries to build it from source.

**Review by TonyBagnall — APPROVED** [review]
I'll try this out

**Pull request merged**
