### PR TITLE
fix #79

### LINKED ISSUE #79: [BUG] ModuleNotFoundError: No module named 'sktime.utils.data_container'
I installed the development version of sktime along with pip version which is `0.5.0`
Sktime-dl development version is installed

I am using colab with following settings
Linux-4.19.112+-x86_64-with-Ubuntu-18.04-bionic
Python 3.6.9 (default, Oct  8 2020, 12:12:24) 
[GCC 8.4.0]
NumPy 1.19.4
SciPy 1.4.1
sktime 0.5.0
sktime_dl 0.2.0

I am getting following error
`ModuleNotFoundError: No module named 'sktime.utils.data_container'`

**Here is the solution**
At this file
`sktime_dl/utils/_data.py`

change
`from sktime.utils.data_container import tabularise, nested_to_3d_numpy`
to
`from sktime.utils.data_processing import from_nested_to_2d_array, from_nested_to_3d_numpy`
and change

`from sktime.utils.validation.series_as_features import check_X, check_X_y`
to
`from sktime.utils.validation.panel import check_X, check_X_y`

### PR DESCRIPTION
**Pull request by talhaanwarch**
Fixes the issue #79

### CODE REVIEW

**Comment by mloning** [comment]
@talhaanwarch thanks for the PR - sktime-dl currently doesn't have a maintainer and it may take some time until we can fix the issues.

**Comment by joshlk** [comment]
@mloning is it as simple as fixing the imports so the CI tests run? If that is the case I don't mind putting in the time and doing that

**Comment by mloning** [comment]
Hi @joshlk - that would be the best case scenario, there may be some other issues to fix though, so hard to tell. We're also thinking about integrating it more closely with sktime. As said on the README, we're currently stretched a bit thin, to properly support sktime-dl, but if you're fairly familiar with TF and CI workflows on GitHub, you're help would be very welcome!

**Comment by joshlk** [comment]
Hi @talhaanwarch, i've pushed fixes to PR #81 . Which also fixes the test suite as well

**Comment by TonyBagnall** [comment]
closing prior to update to sktime 0.6

**Pull request closed without merging**
