### PR TITLE
FCN_refactor

### PR DESCRIPTION
**Pull request by Nanashi06**

### CODE REVIEW

**Comment by TonyBagnall** [comment]
hi sandipan, the network FCNNetwork should go in the network directory, see how CNN is structured

**Comment by Nanashi06** [comment]
> hi sandipan, the network FCNNetwork should go in the network directory, see how CNN is structured

Resolved in the new commit. Kindly check.

**Review by TonyBagnall — APPROVED** [review]
Its in! First PR complete :)

**Comment by TonyBagnall** [comment]
green light to do the rest, thanks

**Pull request merged**
