### PR TITLE
Tensorflow v2

### LINKED ISSUE #16: Tensorflow 2 compatibility
Brought up initially in #15 

TF2 compatibility is definitely something to look into. I'm not sure how big of a job it would be for this repo in particular. Presumably the [automated upgrade process](https://blog.tensorflow.org/2019/02/upgrading-your-code-to-tensorflow-2-0.html) could be applied, though from memory there's very little raw tensorflow code used anyway

Open question of whether to _enforce_ version >=2, or if there are still reasons related to implementation maturity/stability to allow 1.x

### PR DESCRIPTION
**Pull request by Withington**
#### Reference Issues/PRs
Fixes #16
TensorFlow 2 compatibility

#### What does this implement/fix? Explain your changes.

Enable use of TensorFlow 2.0 as a backend.

Added a second build to Travis so there is one that installs TensorFlow 1.15 and one that installs 2.0. These builds run and test fine on my fork. 

Added coveralls to the Travis build in order to view line coverage at coveralls.io. The tests cover 87% of the code and the lines that aren’t covered aren't novel calls to TensorFlow. 

Removed the restriction in setup.py that required install of tensorflow<2 (the restriction was added only a few days ago). Changed setup.py to require install of keras>=2.3.0 because 2.3 is the only version that supports TensorFlow 2.

TensorFlow’s tf_upgrade_v2 script highlighted only one possible issue (regarding model.save) but it is not an issue for sktime-dl because it is using keras, not tf.keras. However, I updated save_trained_model in anticipation of needing to migrate from keras to tf.keras (keras won’t be maintained after April 2020). The default format for saving a tf.keras model switches from h5 in TF1 to TensorFlow SavedModel in TF2. I added the same “save_format” input to save_trained_model and highlighted this potential future change in the function’s docstring.

Switched save_trained_model from using os to pathlib to handle file paths. Now the user can enter model_save_directory with or without the trailing forward slash. Furthermore, pathlib supports Windows and Posix paths. 

Ensemble model – corrected the default model_name - previously it was “InceptionTime”.

#### Any other comments?
Next steps :
+ TensorFlow 2.1 was released on 8 Jan so I’ll start testing this with a view to update next week.
+ Consider migrating from keras to tf.keras – I’ll open an issue.

### CODE REVIEW

**Comment by James-Large** [comment]
All looks good to me, @mloning happy with the addition of coveralls?

**Comment by mloning** [comment]
Any reason for why we go with coverall rather than codecov? Just curious

**Comment by Withington** [comment]
I’ve used coveralls before so it was a quick way for me to check that calls to tensorflow were being tested. It’s worked well for me on other repos. Here is the report https://coveralls.io/github/Withington/sktime-dl 

BTW to generate the coveralls report on this repo, you’d need to sign up to coveralls.io (you can use your GitHub account) and add repo.

**Comment by Withington** [comment]
- TensorFlow 2.0 works fine, the build passes.

-  TensorFlow 2.1 and scikit-learn 0.22 - build fails with "_It seems that scikit-learn has not been built correctly_."

- TensorFlow 2.1 and scikit-learn 0.21.3 works fine, the build passes.

I suggest sticking with TensorFlow 2.0 for now. I updated the README to say that TF 2.0 is supported. Could you go ahead and merge this PR or is anything else required?

**Pull request merged**
