### PR TITLE
CI cron job for slow tests

### PR DESCRIPTION
**Pull request by mloning**
#### What does this implement/fix? Explain your changes.
Runs all tests on a daily basis if there have been changes to the source code on dev and master, including slow ones, to guarantee reproducibility of published results. 

#### Reference Issues/PRs
As discussed in #51

### CODE REVIEW

**Comment by mloning** [comment]
@Withington the forecaster tests fail with nan values, any idea? Should we make them into flaky tests?

**Comment by Withington** [comment]
How often is it failing with NaN, just this one time? They’ve been fine up until now so has something changed?

**Comment by mloning** [comment]
I'm also not sure why this comes up now, haven't changed any source code, only the azure yaml files ... restarted the tests.

**Comment by mloning** [comment]
Now they pass, looks like a flaky case to me :-)

**Comment by mloning** [comment]
This is good to go from my side. Let me know what you think @Withington @James-Large

**Comment by Withington** [comment]
Will the cron job run on PRs too?

**Comment by mloning** [comment]
I'm actually not sure, we'll have to see, but if we want it to run for all PRs I could add it to the `ci.yml`, that may be easier

**Pull request merged**
