### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by James-Large**
Long time no PR, getting this into master before working on new things. Proposing that this updates sktime-dl to 0.2.0

See #14 for most of the changes. 

Major:

- added the inception time TSC model (https://github.com/hfawaz/InceptionTime)
- introduction of meta package on top level, housing generic ensemble and tuning classes and their tests
- capability to save trained models added (back in, to some extent). Default off
- readme semi-overhaul (somewhat preempting setup.py changes, see below)

Also included are some updates to the setup.py and travis tests.

### CODE REVIEW

**Comment by mloning** [comment]
Let's wait for the regressor refactoring on #22 before me make a new release!

**Comment by Withington** [comment]
The pull request build failure above failed with ```ValueError: Error when checking target: expected dense_9 to have shape (1,) but got array with shape (2,)```
I've seen this a few times on MCDCNN on other branches and with TensorFlow 1. It isn't an issue unique to this Pull Request.

**Comment by Withington** [comment]
The dev branch build on my fork passed - 
https://travis-ci.com/Withington/sktime-dl/builds/146884445

**Comment by Withington** [comment]
I'm eager to get these new features into master and into pypi. Aside from the other two open pull requests, is there anything else you want in prior to merging dev to master?

**Comment by mloning** [comment]
I was hoping to update/automise the distribution/release process before the next release (see [#196](https://github.com/alan-turing-institute/sktime/issues/196)), but we also can add this later when we update it in base sktime.

**Comment by Withington** [comment]
Are you going to try deploying it to pypi using [Travis](https://docs.travis-ci.com/user/deployment/pypi/)?

**Comment by Withington** [comment]
I've added PR / draft PR #42 #43 #44 but I'm happy if those need to wait until after this PR to merge dev to master.

**Comment by mloning** [comment]
Yes, I'd like to upload to pypi via travis on tagged commits, but I think that can wait until later. sktime is a bit more complicated too because it's not a pure Python package, so we have to distribute platform-specific wheels.

**Comment by James-Large** [comment]
My lord, the tests passed. Validation tests have been marked as slow and not to run on travis, as too often there's one or two envs where it hits the 10 min time out while the rest are fine.

After release, there'll be some issues put up and we'll do a roadmap post for 0.3.0 in the future, one of them will be revamping the tests and streamlining them. Part of me dreads merging this and then one of the tests fails due to bad initialisation again on master

Either way, think this is a long over due merge. Good to submit reviews?

**Comment by Withington** [comment]
Thanks for persevering @James-Large. Good to merge 👍

**Review by mloning — APPROVED** [review]
Yes, I'm happy to merge too!

**Comment by mloning** [comment]
Sorry for the delay!

**Comment by Withington** [comment]
Fantastic to see this merge go through 🥳
What is the next step to get it released on pypi?
@James-Large @mloning

**Comment by mloning** [comment]
@Withington I don't think we've set up the CI so that tags automatically trigger uploads to pypi. Implementing that would be really helpful. The sktime base repo could serve as an example. Otherwise we can do it by downloading the build artefacts and  manually uploading them pypi.

**Pull request merged**
